title: Extended Reality Landscape
tag-line: Mapping the global activity 

url: https://extendedrealitylandscape.com/

permalink: pretty
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

kramdown:
    smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]

encoding: utf-8

# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
